export { authService } from './auth.service'
export { productService } from './product.service'
export { dashboardService } from './dashboard.service'
export { uploadService } from './upload.service'
export { stockService } from './stock.service'
export { compositionService } from './composition.service'
export { shopService } from './shop.service'
export { categoryService } from './category.service'
// export { profileService } from './profile.service'
export { locationService } from './location.service'